#+TITLE: Software Defined Communication System
#+AUTHOR: Adithya Nair
#+LATEX_HEADER: \input{preamble}
#+LATEX_CLASS: report

* Unit 1
** Convolutions
\begin{definition}[Convolution]
A convolution is an integral that expresses the amount of overlap of one function $f(t)$, as it is shifted over to function $g(t)$, for a continuous time signal.
\[
(f * g)(t) = \int_{-\infty}^{\infty} f(\tau)g(t - \tau) d \tau
\]
\end{definition}
When working with discrete signals, the integral becomes a summation.
So the convolution $Y[h] $
\[
Y[h] = \Sum_{k = -\infty}^{\infty} x(k) h(n-k)
\]
#+begin_src octave :results output
h = [0 1 2 3;2 4 1 3]';
reverse = @(H)[-1*H(:,1) H(:,2)];
timeRH = reverse(h)
#+end_src

#+RESULTS:
: timeRH =
:
:    0   2
:   -1   4
:   -2   1
:   -3   3
:

#+begin_src octave
clc;
clear all;
close all;
% Define the original signal
x = [1 2 3 4];
% Define the time indices for plotting
n = 0:length(x)-1;
n_reversed = -fliplr(n);
% Time-shifted versions
x_n1 = [0 x(1:end-1)]; % Shifting right, padding with 0 at the beginning
x_np1 = [x(2:end) 0]; % Shifting left, padding with 0 at the end
x_neg_n = fliplr(x); % Reversing the sequence
x_neg_np1 = [fliplr(x(2:end)) 0]; % x[-n+1]
% Plotting
subplot(2,2,1); stem(n, x); title('x[n]');
subplot(2,2,2); stem(n, x_n1); title('x[n-1]');
subplot(2,2,3); stem(n, x_np1); title('x[n+1]');
subplot(2,2,4); stem(n_reversed, x_neg_n); title('x[-n]');
% Plot x[-n+1] separately due to different time axis
figure;
stem(n_reversed+1, x_neg_np1); title('x[-n+1]');
#+end_src
** Real Sinusoid
A rotation of two complex sinusoidal signals in opposite directions to each other.
- $V(t)$ with a frequency F shown as solid blue line with $V*(t)$ with frequency -F shown as dashed red line
- The I parts exactly fall on top of each other and hence are the same $cos 2\pi Ft$
- The Q parts carry exactly the same amplitude with opposite signs to each other and hence are $sin 2\pi Ft$ and $-sin 2\pi Ft$

$$|V \cdot V^*| = |V|^2 = V_I^2 + V_q^2$$

It is a combination of two complex signals.

* Revision
** Chapter 1
*** Signal Energy And Power
$$E = \int_{-\infty}^{\infty}|x(t)|^2dt$$
$$P \lim_{T \rightarrow \infty} \frac{1}{T} \int_{-T/2}^{T/2} |x(t)|^2dt$$
*** Time Invariance
- No time scaling
- Coefficient should be not be time dependent.
- Any addition or subtraction term to the system, should be constant or zero.
*** Linearity
- Any linear  system is independent of time scaling
- If the order of system is greater than 1, then it is not linear.
*** Discrete Convolution
$$y[n] = \Sigma_{k = -\infty}^{\infty}x[k]h[n-k]$$
*** Complex Numbers
- Inphase, $V_I = |V| \cos(V)$
- Quadrature $V_Q = |V| \sin(V)$
*** Complex Sinusoids
- V rotating anticlockwise at a constant rate
- Made up of two real sinusoids.
- Complex sinusoids with frequency F is composed of,
  \begin{align*}
  V_I = \cos 2 \pi Ft \\
  V_Q = \sin 2 \pi Ft \\
  \end{align*}
*** Filters
- Low pass
  Capacitor in parallel and inductor in series
- High pass
- Band pass
- Band stop
- Band reject
- Notch
**** Pass Band
Range of frequences in which the filter allows the signal to pass
**** Stop Band
Range of frequences which will reject passage
** Chapter 2
*** Modulation
Reduces the size of antenna
$L \propto \lambda$ and $\lambda = \frac{c}{f}$

Value of the modulating signal,

$v_1 = V_c + v_m = V_c + V_m \sin{2 \pi f_m t}$
$v_{2} = v_{1} sin 2\pi f_ct$

$m = \frac{V_m}{V_c}$ Modulation index

*** AM Power
$$P_T = P_c + P_{USB} + P_{LSB}$$
$$P_T = \frac{V_c^2}{2R} + \frac{V_m^2}{4R}$$

So with modulation index,

$$P_T = P_c(1 + \frac{m^2}{2})$$
*** AM DSB SC
- 2/3 of power in carrier
*** Efficiency
$$\mu = \frac{P_{USB} + P_{LSB}}{P_{T}}$$
$$\mu = \frac{\mu^2}{\mu^{2} + 2}$$
*** AM-SSB
**** AM-SUSB
$$A_i A_c \cos(\omega_c + \omega_i)t$$
**** AM-SLSB
$$A_iA_ccos(\omega_c - \omega_{i})t$$
*** Hilbert Transform
Converts cosine function into sine function by convolution of $\cos(\phi(t))$ with $\frac{1}{\pi t}$
* Lab
** Sampling Theorem
#+begin_src octave :results output
clc;
close all;
clear all;
f1=3;
f2=23;
t=-0.4:0.0001:0.4;
x=sin(2*pi*f1*t)+cos(2*pi*f2*t);
figure(1);
plot(t,x,'-.r');
xlabel('time-----');
ylabel('amp---');
title('The original signal');
%case 1: (fs<2fm)
fs1=1.4*f2;
ts1=1/fs1;
n1=-0.4:ts1:0.4;
xs1=cos(2*pi*f1*n1)+cos(2*pi*f2*n1);
figure(2);
stem(n1,xs1);
hold on;
plot(t,x,'-.r');
hold off;
legend('fs<2fm');
%case 2: (fs=2fm)
fs2=2*f2;
ts2=1/fs2;
n2=-0.4:ts2:0.4;
xs2=cos(2*pi*f1*n2)+cos(2*pi*f2*n2);
figure(3);
stem(n2,xs2);
hold on;
plot(t,x,'-.r');
hold off;
legend('fs=2fm');
%case 3: (fs>2fm)
fs3=7*f2;
ts3=1/fs3;
n3=-0.4:ts3:0.4;
xs3=cos(2*pi*f1*n3)+cos(2*pi*f2*n3);
figure(4);
stem(n3,xs3);
hold on;
plot(t,x,'-.r');
hold off;
legend('fs>2fm');
#+end_src

#+RESULTS:
* Practice
** Generate basic signals
Use the required blocks for the scopes.
1. Ramp
2. Step
3. Sine
4. Square Wave Generator
5. Triangle Wave Generator
** Convolution
*** Discrete Convolution
Use two constant block parameters and connect them to a convolution block and then make a scope(discrete convolution)
*** Continous Convolution
Two signal blocks and connect them to a convolution block and then make a scope(continuous convolution)
** Find FFT Of A Signal
1. Put a Signal Block Parameter
2. Connect it to a zero-order hold(sample time, same as question)
3. Connect that to a buffer(Output buffer size 1024)
4. Connect it to FFT block
5. Add a gain(1/buffer size)
6. Add Abs
7. Spectrum Analyzer
** TODO Find Time Invariance Of Given System
** Generate A Square Wave From Odd Harmonics
1. Make 7 Sine Waves - (f = 2*pi*1 - 2*pi 13)
2. Add a gain for each of these waves (1 - 1/13)
3. Adder(connect all these waves)
** Generate An AM Signal Using Simulink
- Ingredients
  1. Use two signal generators to generate the message and carrier signal
  2. Bring in a constant block(modulation index)
  3. Adder block
  4. Product block
  5. 3 Zero Order Holds
  6. Spectrum Analyzer
- Connect message signal generator to the message zero order hold
- Similarly do so for the carrier signal
- The output of the product(modulator) goes to the last zero order hold
- Message signal and modulation index is added through the adder block
- The output of the adder block along with the carrier signal goes to the product(modulator)
- 3 Inputs For The Spectrum Analyzer
  1. Message Zero Order Hold
  2. Carrier Zero Order Hold
  3. AM Modulator Zero Order Hold
- Scope requires 3 inputs
  1. Message Signal
  2. Carrier Signal
  3. AM Modulator Signal
- Finally in the spectrum analyzer, click Peak Finder and adjust number of peaks(For the Amplitude Modulation)
** Generate A DSB-SC Signal Using Simulink
Same as above, but the modulation index and the adder block
** Generate an SSB with or without a filter using Simulink
** Perform Operations On Basic Signals
1. Multiply (Product block)
2. Add (Adder block)
3. Flip (Gain block with gain = -1)
4. Shift (Transport Delay Block, Time delay = given in question)
*** Observation
*** Inference
** Analyzing Appropriate Sampling Rate
1. Take the given sine wave and add it with pulse generator(also can use step or ramp)
