#+TITLE: Software Defined Communication System
#+AUTHOR: Adithya Nair
#+LATEX_HEADER: \input{preamble}
#+LATEX_CLASS: report
* Notes
** Unit 1
*** Classification Of Systems
- No. of inputs - SISO, MIMO
- Type of signal - Continuous time-system, discrete
- Dimension - One-dimensional, multi-dimensional
*** Even And Odd Signals
**** Even Signal
$$x(t) = x(-t)$$
**** Odd Signal
$$x(t) = -x(-t)$$
*** Signal Energy And Power
$$E = \int_{-\infty}^{\infty}|x(t)|^2dt$$
$$P \lim_{T \rightarrow \infty} \frac{1}{T} \int_{-T/2}^{T/2} |x(t)|^2dt$$
*** Linear Time Invariance
**** Why LTI?
- The effect of a system on the spectrum can be analyzed easily if and only if the system is LTI.
**** How To Check Time Invariance
- No time scaling
- Coefficient should be not be time dependent.
- Any addition or subtraction term to the system, should be constant or zero.
*** Linearity
- Any linear  system is independent of time scaling
- If the order of system is greater than 1, then it is not linear.
*** Discrete Convolution
$$y[n] = \Sigma_{k = -\infty}^{\infty}x[k]h[n-k]$$
*** Sinusoids
**** Why Do We Need Sinusoids?
- Used in modulation schemes
- Used in communication systems
- Any signal can be represented as a sum of sinusoids.
- Filters and equalizers can be characterized by their response
*** Complex Numbers
- Inphase, $V_I = |V| \cos(V)$
- Quadrature $V_Q = |V| \sin(V)$
*** Complex Sinusoids
- V rotating anticlockwise at a constant rate
- Made up of two real sinusoids.
- Complex sinusoids with frequency F is composed of,
  \begin{align*}
  V_I = \cos 2 \pi Ft \\
  V_Q = \sin 2 \pi Ft \\
  \end{align*}
*** Filters
**** Primary Functions
- To confine a signal into a prescribed frequency band.
- To decompose a signal into two or more sub-band signals for sub-band signal processing, in music
- To modify frequency spectrum
- To model input output relation of a system.
**** Types Of Filters
- Low pass
  Capacitor in parallel and inductor in series
- High pass
- Band pass
- Band stop
- Band reject
- Notch
**** Pass Band
Range of frequences in which the filter allows the signal to pass
**** Stop Band
Range of frequences which will reject passage
** Unit 2
*** Modulation
Why do modulation?
- Reduces the size of antenna $$L \propto \lambda \text{ and } \lambda = \frac{c}{f}$$

- To reduce interference
- To improve SNR($\frac{\text{Power Of Signal}}{{Power Of Noise}}$)
- To allow multiplexing of the signals
- Optimizes bandwidth utilization
Value of the modulating signal,

$$v_1 = V_c + v_m = V_c + V_m \sin{2 \pi f_m t}$$
$$v_{2} = v_{1} sin 2\pi f_ct$$

$$\text{Modulation Index}, m = \frac{V_m}{V_c}$$

*** Over-Modulation
When $V_m > V_{c}$, over-modulation. Automatic circuits called compression circuits solve this problem by amplifying the lower signals and suppressing or compressing the higher level signals
*** Side-Band Calculation
$$V_{AM} = V_C sin 2 \pi f_c t + (V_m sin 2 \pi f_c t)(sin 2 \pi f_c t)$$
$$V_{AM} = V_C sin 2 \pi f_c t + \frac{V_m}{2} cos 2 \pi t (f_c - f_m) - \frac{V_{m}}{2} \cos 2 \pi t (f_c + f_{m}) $$

\begin{align*}
f_{USB} = f_c + f_m \\
f_{LSB} = f_c - f_m \\
\end{align*}
**** Types Of Modulation
1. Analog Modulation
   - Amplitude Modulation
   - Frequency Modulation
   - Phase Modulation
2. Digital Modulation
*** Analog Modulation
**** Total Power
For power calculation, rms value is used.
$$P_T = P_C + P_{USB} + P_{LSB}$$
****
**** Power In Terms Of Modulation Index
$$P_T = P_C(1 + \frac{m^2}{2})$$
*** Types Of Amplitude Modulation
**** Double SideBand - Suppressed Carrier

$$s_{am-dsb-sc}(t) = \frac{A_iA_c}{2}(cos(\omega_c- \omega_i)t + cos((\omega_c + \omega_i)t)$$

- In AM, 2/3rds of the transmitted power is in the carrier, which conveys no information
- No power is wasted on the carrier
- It's given an efficiency of 50%
- Used in transmission of color info in a TV signal.
***** Transmission Efficiency
$$\eta = \frac{P_{USB} + P_{LSB}}{P_{T}} = \frac{\mu^2}{\mu^2 + 2}$$

**** Single SideBand
- The primary benefit is that it occupies only half of AM-DSB
- SSB signals occupy narrower bandwidth so less signal noise
- Less selective fading of SSB signal over long distances.

$$s_{am-susb}(t) = \frac{A_iA_c}{2}cos((\omega_c + \omega_i)t)$$
$$s_{am-slsb}(t) = \frac{A_iA_c}{2}cos((\omega_c - \omega_i)t)$$
***** Advantages
- Half the bandwidth is required compared to DSB
- Due to suppression of carrier and one sideband power is saved
- Reduced noise interference due to to reduced bandwidth
***** Disadvantages
- Generation and reception of SSB signals are complex
- SSB transmitter and receiver need to have an excellent frequency stability
- SSB modulation is expensive and complex to implement.
***** Applications
- Used at HF segment of the spectrum(for frequency below 10MHz-LSB, above 10MHz - USB)
- Used where power saving is required
- Also used in low bandwidth requirements
**** Vestigial SideBand
- Used to reduce the spectral requirements of analog TV
- Apply BPF to AM-DSB-TC signals to suppress most of the sidebands.
- In VSB, one sideband and part of the other sideband is transmitted
- Bandwidth is slightly higher than SSB
- Easier to implement than SSB.
*** Amplitude Demodulation
**** Coherent AM Demodulation
To demodulate an AM signal, a recover must multiply the received signal with a sine wave, that has exactly the same frequency and phase as the carrier embedded within it.

The mixing operation shifts the modulated information from being centered around carrier frequency back to baseband.
***** Demodulation of AM-DSB-SC signals
Given that the sine wave synthesized with the same frequency and phase
$$s_d = \frac{A_iA_c}{2}\cos{\omega_i t}$$
**** Non-coherent AM Demodulation
- During the positive half cycle diode conducts and the capacitor charges to the peak voltage.
- During -ve half cycle capacitor discharges
- Because the capacitor charges and discharges, the recovered signal has a small amount of ripple
- Distortion occurs when the time constant of resistor and capacitor is too long or too short.
- If the time constant is too long, the discharge is too slow to follow the faster changes in the modulated signal.
*** Frequency Modulation
- The carrier amplitude remains constant, the carrier frequency is changed by the modulating signal.
- If amplitude of modulating signal increases, frequency increases, if amplitude decreases, frequency decreases
- Change in carrier frequency produced by modulating frequency is $f_d$.
- FM is used for commercial radio.
**** Voltage Controlled Oscillator
$$\hat{\theta}(t) = k_o \int_{-\infty}^t v(t) dt$$
 * $k_o$ - voltage to frequency gain ratio
 * integrated(change phase by 90)

   $$s_{fm} = A_c \cos{\omega_c t + 2 \pi K_{fm} \times \int_{-\infty}^ts_i(t) dt}$$
**** Modulating a sine wave
$$s_i = A_i \cos{\omegas_i t}$$
$$s_{fm} = A_c \cos{(\omega_{c} t) + \beta_{fm} \cos{\omegas_i t}$$

Where,
- $\beta_{fm}$ - modulating index($\frac{\Delta f}{f_i}$)

The instantaneous frequency is

$$f_{fm} = f_c + K_{fm} s_i(t)$$

**** Sidebands
In FM, a large number of sidebands are generated. These sidebands are of the form, $f_c \pm kf_m$
*** Types Of FM
- Narrowband FM
  $$\beta_{fm} << \frac{\pi}{2} or 1$$

  $$s_{fm-nfm} = A_c [\cos{\omega_c t} + \frac{\beta_{fm}}{2}\cos(\omega_c+ \omega_{i} t)+ \frac{\beta_{fm}}{2}\cos(\omega_c - \omega_{i} t)]$$
- Wideband FM
  $$\beta_{fm} >> \frac{\pi}{2} or 1$$
**** Advantages Of FM Over AM
- Improved Signal-To-Noise Ratio
- Better Sound Quality
- Reduced Distortion
*** Phase Alternating Line
PAL is a composite video because luminance(luma, monochrome image) and chrominance(chroma, color applied to monochrome) are transmitted as one signal.
