#+title: Journal Club
#+author: Adithya Nair
#+LATEX_CLASS: report
#+LATEX_HEADER: \input{preamble}
The textbook is Terrence Tao's Analysis 1.
* Real Analysis
** Introduction
Real Analysis is useful for engineers and physicists. It's said to have a bad reputation, due to its rigour. This textbook offsets that by starting at the very base, the numbers themselves. It starts by defining natural numbers, then building integers, rational, real, complex and so on.
We have the continuous medium which is expressed by the PDEs, Dynamics expressed by ODEs. Computer scientists aren't taught this,  they're taught Discrete Math.
** Natural Numbers
Numbers were built to count. A system for counting was made, and that system is the number system.

\begin{definition}
A natural number is an element of the set $\mathbb{N}$ of the set
\[
\mathbb{N} = \{0,1,2,3\cdots \}
\]
is obtained from 0 and counting forward indefinitely.
\end{definition}
*** Peano Axioms
We start with axioms to help clarify this.
- Axiom 1 : $0 \in \mathbb{N}$
- Axiom 2: If $n \in \mathbb{N}$,, then $n++ \in \mathbb{N}$
This means that we have 0, 0++, ((0++)++)++ ...
 We can then give these numbers  symbols for ease, 0,1,2,3... NOTE: They do not hold any quantity as yet. They simply exist as representations of 0, 0++ and so on.
- Axiom 3: 0 is not an increment of any other natural number $n \in \mathbb{N}$
- Axiom 4: If $n \neq m$, $n++ \neq m++$
We need to remove the rogue elements from the set, such as fractions and half-integers.
- Axiom 5: (Principle Of Mathematical Induction) Let $P(n)$ be any property pertaining to a natural number $n$. Suppose that $P(0)$ is true, and suppose that whenever $P(n)$ is true, $P(n++)$ is also true. Then $P(n)$ is true for every natural number.

We then make an assumption: That the set $\mathbb{N}$ which satisfies these five axioms is called the set of natural numbers.
With these 5 axioms, we can construct sequences
*** Sequences
For $n \in \mathbb{N}$
\begin{align*}
a_0 &= c, c \in \mathbb{N} \\
a_1 &= f_0(a_0), \\
a_2 &= f_1(a_1), \\
&\vdots \\
a_{n++} &= f_n(a_n), \\
\end{align*}

\begin{prop}
An operation $f$ which operates on any number $n$ in \mathbb{N}
\begin{align*}
f_n: \mathbb{N} &\rightarrow \mathbb{N} \\
\forall n &\in \mathbb{N}, \exists! \ a_n \text{ such that } \\
a_0 &= c \\
a_{n++} &= f_n(a_n) \\
\end{align*}
\end{prop}

\begin{definition}[Addition Of Natural Numbers]
Let n be a natural number. $(n \in N)$. To add zero to m, we define $0+m:=m$ Now suppose inductively that we have defined how to add $n$ to $m$. Then we can add $n++$ to $m$ by defining($n++$) + m := (n+m)++
\end{definition}

\begin{lemma}
For any natural number $n + 0=n$
\end{lemma}
\begin{proof}
\begin{align*}
n &= 0, 0 + 0 = 0 \\
n+0 &= n \\
(n++) + 0 &= (n+0)++ = n++ \\
\end{align*}
\end{proof}
\begin{lemma}
\[
n + (m++) = (n+m)++
\]
\end{lemma}
\begin{proof}
\begin{align*}
n &= 0, \\
0 + m++ = (0+m)++ \\
For
(n++) + (m++) &= ((n++)+m)++ \\
&=(n+(m++))++ \\
&=((n+m)++))++ \\
\end{align*}
\end{proof}

Putting m = 0, we get $n+1 = n++$
\begin{definition}[Positive natural number]
All numbers where,
\[
n \neq 0, n \in \mathbb{N}
\]
\end{definition}

\begin{lemma}
For every $a$, there exists a $b$ such that $b++ = a$
\end{lemma}

\begin{definition}[Order]
Let n and m be natural numbers we say that $n$ is greater than or equal to m, and write $n \geq m$ iff we have $n = m + a$ for some natural number $a$. We say that $n > m$ when $n \geq m$ and $n \neq m$
\end{definition}
*** Multiplication
#+begin_definition
Let $m$ be a natural number. To multiply zero to $m$, we define $0 \times m := 0$. Now suppose inductively that we have defined how to multiply $n$ to $m$. Then we can multiply $n++$ to $m$ by defining $(n++) \times m := (n \times m) + m$
#+end_definition
#+begin_lemma
Prove that multiplication is commutative
#+end_lemma
