#+title: Journal Club
#+author: Adithya Nair
#+LATEX_CLASS: report
#+LATEX_HEADER: \input{preamble}
* Real Analysis
TEXTBOOK: [[file:~/University-Latex-Notes/Journal Club/Analysis I - Tao.pdf][Analysis 1 by Terence Tao]]
** Natural Numbers
Numbers were built to count. A system for counting was made, and that system is the number system.
\begin{definition}
A natural number is an element of the set $\mathbb{N}$ of the set
\[
\mathbb{N} = \{0,1,2,3\cdots \}
\]
is obtained from 0 and counting forward indefinitely.
\end{definition}
*** Peano Axioms
We start with axioms to help clarify this.
- Axiom 1 : $0 \in \mathbb{N}$
- Axiom 2: If $n \in \mathbb{N}$,, then $n++ \in \mathbb{N}$
- Axiom 3: 0 is not an increment of any other natural number $n \in \mathbb{N}$
- Axiom 4: If $n \neq m$, $n++ \neq m++$
- Axiom 5: (Principle Of Mathematical Induction) Let $P(n)$ be any property pertaining to a natural number $n$. Suppose that $P(0)$ is true, and suppose that whenever $P(n)$ is true, $P(n++)$ is also true. Then $P(n)$ is true for every natural number.

We then make an assumption: That the set $\mathbb{N}$ which satisfies these five axioms is called the set of natural numbers.
With these 5 axioms, we can construct sequences
*** Recursive Definitions
#+ATTR_LATEX: :options [Recursive Definitions]
#+BEGIN_prop
Suppose for each natural number $n$, we have some function $f_n:\mathbb{N} \rightarrow \mathbb{N}$ from the natural numbers to the natural numbers. Then we can assign a unique natural number $a_n$ to each natural number $n$, such that $a_0 = c$ and $a_{n++} = f_n(a_n)$ for each natural number $n$.
#+END_prop
*** Addition
\begin{definition}[Addition Of Natural Numbers]
Let n be a natural number. $(n \in N)$. To add zero to m, we define $0+m:=m$ Now suppose inductively that we have defined how to add $n$ to $m$. Then we can add $n++$ to $m$ by defining($n++$) + m := (n+m)++
\end{definition}

\begin{lemma}
For any natural number $n + 0=n$
\end{lemma}
\begin{proof}
We use induction,

The base case, n = 0,
\begin{align*}
n &= 0, 0 + 0 = 0 \\
n+0 &= n \\
(n++) + 0 &= (n+0)++ = (n++)
\end{align*}

Suppose inductively, that $n+0=n$,

For $n=n++$,
\begin{align*}
(n++) + 0 &= (n+0)++ \\
\text{We know that $n+0=n$} \\
(n++) + 0 &= (n++)
\end{align*}
\end{proof}

\begin{lemma}
For any natural numbers $n$ and $m$,
$$n + (m++) = (n+m)++$$
\end{lemma}
\begin{proof}
Inducting on $n$ while keeping $m$ fixed,
\begin{align*}
n &= 0, \\
0 + (m++) &= (0+m)++ \\
0 + (m++) &= (m++)
\end{align*}
This we know is true from the definition of addition $(0+m:=m)$

Suppose inductively, that $n+(m++) = (n+m)++$ is true.
For $n=(n++)$,
\begin{align*}
(n++) + (m++) &= ((n++)+m)++ &\text{From the definition of addition} \\
&=(n+(m++))++ \\
&=((n+m)++))++
\end{align*}
\end{proof}

Putting m = 0, we get $n+1 = n++$

\begin{prop}[Addition is commutative]
For any natural numbers $n$ and $m$, $n+m=m+n$
\end{prop}
\begin{proof}
We induct over $n$,
For the base case, $n=0$,

We must show that $m+0 = 0+m$
From the definition of addition, we have
$$0+m = m$$

As shown earlier, we have

$$m+0 = m$$

This is clearly true for $n=0$.

Now suppose inductively that $m+n = n+m$

For $n=n++$, we must show that $m+(n++) = (n++) + m$

We know from the definition of addition that,

$$(n++) + m := (m+n)++$$

And we proved earlier that,

$$m+(n++) = (m+n)++$$

Therefore,

$$m+(n++) = (n++)+m$$
\end{proof}
\begin{prop}[Addition is associative]
For any natural numbers, $a,b$ and $c$, we have $(a+b)+c = a+(b+c)$
\end{prop}
\begin{proof}
We take $(a+b)+n = a + (b+n)$

Inducting over n,

For $n=0$,

We have in the LHS,
\begin{align*}
&=(a+b)+0 &\text{Since $n+0 = n$}\\
&=a+b
\end{align*}

On the RHS,
\begin{align*}
&=a + (b+0) &\text{Since $n+0 = n$}\\
&=a + b
\end{align*}

Suppose inductively that $(a+b)+n = a+(b+n)$,

For $n=n++$,
We have to show that $(a+b)+(n++) = a+(b+(n++))$

On the LHS we have,

\begin{align*}
&=(a+b)+(n++) \\
&=(a+b+n)++ &\text{(From the lemma $m+(n++) = (m+n)++$)} \\
\end{align*}

On the RHS we have,

\begin{align*}
&=a+(b+(n++)) \\
&=a+(b+n)++ &\text{(From the lemma $m+(n++) = (m+n)++$)} \\
&=(a+b+n)++
\end{align*}

LHS = RHS
\end{proof}

\begin{prop}[Cancellation Law]
Let $a,b,c$ be natural numbers such that $a+b=a+c$. Then we have $b=c$.
\end{prop}
\begin{proof}
We have,
$$n+b=n+c$$

Inducting over n,
For the base case, $n=0$
\begin{align*}
0 + b &= 0 + c \\
b &= c
\end{align*}

Suppose inductively that $n+b=n+c$
For $n=n++$,
$$(n++)+b=(n++)+c$$
On the LHS
\begin{align*}
&=(n++) + b \\
&=(n+b)++
\end{align*}

On the RHS
\begin{align*}
&=(n++) + c \\
&=(n+c)++
\end{align*}

We know from the inductive hypothesis that,
$$\text{If} n+b = n+c, \text{then} b = c$$

Thus we have,
$$b++ = c++$$
\end{proof}

\begin{definition}[Positive natural number]
All numbers where,
\[
n \neq 0, n \in \mathbb{N}
\]
\end{definition}

\begin{lemma}
For every $a$, there exists a $b$ such that $b++ = a$
\end{lemma}

\begin{definition}[Order]
Let n and m be natural numbers we say that $n$ is greater than or equal to m, and write $n \geq m$ iff we have $n = m + a$ for some natural number $a$. We say that $n > m$ when $n \geq m$ and $n \neq m$
\end{definition}

*** Strong Induction
#+begin_theorem
Let $m_0$ be a natural number, and let $P(m)$ be a property pertaining to an arbitrary natural number $m$. Suppose that for each $m \geq m_0$, we have the following implication: if $P(m')$ is true for all natural numbers $m_0 \leq m' < m$, then $P(m)$ is also true.(In particular this means that $P(m_0$ is true, since in this case the hypothesis is vacuous.) Then we can conclude that $P(m)$ is true for all natural numbers $m \geq m_0$.
#+end_theorem
#+begin_proof
For a property $Q(n)$, which is the property that $P(m')$ is true for $m_0 \leq m' < n$, then $P(n)$ is true.

For $Q(0)$,
$0$ is either lesser than or equal to $m_0$.

When $0$ is lesser than $m_0$,

This is vacuously true.

When $0 = m_0$,
#+end_proof

*** Induction Starting From The Base Case n
#+BEGIN_proposition
Let n be a natural number, and let P(m) be a property pertaining to the natural numbers such that whenever P(m) is true, P(m++) is true. Show that if P(n) is true, then P(m) is true for all m ≥ n. (This principle is sometimes referred to as the principle of induction starting from the base case n.)
#+END_proposition
#+BEGIN_proof
Take a property $P(n)$, $m \geq n$

Inducting over $n$,
#+END_proof
*** Multiplication
#+begin_definition
Let $m$ be a natural number. To multiply zero to $m$, we define $0 \times m := 0$. Now suppose inductively that we have defined how to multiply $n$ to $m$. Then we can multiply $n++$ to $m$ by defining $(n++) \times m := (n \times m) + m$
#+end_definition
#+begin_lemma
Prove that multiplication is commutative
#+end_lemma

*** Exercise
**** Prove the identity $(a+b)^2 = a^2 + 2ab + b^2$
**** (Euclid's division lemma)
**** Backward Induction
$m \in \mathbb{N}, P(m), P(m++) \implies P(m)$, Suppose $P(n)$ is true, then $P(m) \forall m \le n$
For the base case, n = 0,
P(0) \implies P(0), so it's true.

For the inductive step, supposing $Q(n)$ is true,
**** Strong induction
**** Distributive Law
**** Multiplication
***** Cancellation Law
***** Associativity
***** If a<b, and c is positive then ac<bc

