#+title: Journal Club
#+author: Adithya Nair
#+LATEX_CLASS: report
#+LATEX_HEADER: \input{preamble}
#+EXPORT_FILE_NAME: exports/journal-club.pdf
* Real Analysis
TEXTBOOK: [[file:~/University-Latex-Notes/Journal Club/Analysis I - Tao.pdf][Analysis 1 by Terence Tao]]
** Natural Numbers
Numbers were built to count. A system for counting was made, and that system is the number system.
\begin{definition}
A natural number is an element of the set $\mathbb{N}$ of the set
\[
\mathbb{N} = \{0,1,2,3\cdots \}
\]
is obtained from 0 and counting forward indefinitely.
\end{definition}
*** Peano Axioms
We start with axioms to help clarify this.
- Axiom 1 : $0 \in \mathbb{N}$
- Axiom 2: If $n \in \mathbb{N}$,, then $n++ \in \mathbb{N}$
- Axiom 3: 0 is not an increment of any other natural number $n \in \mathbb{N}$
- Axiom 4: If $n \neq m$, $n++ \neq m++$
- Axiom 5: (Principle Of Mathematical Induction) Let $P(n)$ be any property pertaining to a natural number $n$. Suppose that $P(0)$ is true, and suppose that whenever $P(n)$ is true, $P(n++)$ is also true. Then $P(n)$ is true for every natural number.

We then make an assumption: That the set $\mathbb{N}$ which satisfies these five axioms is called the set of natural numbers.
With these 5 axioms, we can construct sequences
*** Recursive Definitions
\begin{prop}[Recursive Definitions]
Suppose for each natural number $n$, we have some function $f_n:\mathbb{N} \rightarrow \mathbb{N}$ from the natural numbers to the natural numbers. Then we can assign a unique natural number $a_n$ to each natural number $n$, such that $a_0 = c$ and $a_{n++} = f_n(a_n)$ for each natural number $n$.
\end{prop}
*** Addition
\begin{definition}[Addition Of Natural Numbers]
Let n be a natural number. $(n \in N)$. To add zero to m, we define $0+m:=m$ Now suppose inductively that we have defined how to add $n$ to $m$. Then we can add $n++$ to $m$ by defining($n++$) + m := (n+m)++
\end{definition}

\begin{lemma}
For any natural number $n + 0=n$
\end{lemma}
\begin{proof}
We use induction,

The base case, n = 0,
\begin{align*}
n &= 0, 0 + 0 = 0 \\
n+0 &= n \\
(n++) + 0 &= (n+0)++ = (n++)
\end{align*}

Suppose inductively, that $n+0=n$,

For $n=n++$,
\begin{align*}
(n++) + 0 &= (n+0)++ \\
\text{We know that $n+0=n$} \\
(n++) + 0 &= (n++)
\end{align*}
\end{proof}

\begin{lemma}
For any natural numbers $n$ and $m$,
$$n + (m++) = (n+m)++$$
\end{lemma}
\begin{proof}
Inducting on $n$ while keeping $m$ fixed,
\begin{align*}
n &= 0, \\
0 + (m++) &= (0+m)++ \\
0 + (m++) &= (m++)
\end{align*}
This we know is true from the definition of addition $(0+m:=m)$

Suppose inductively, that $n+(m++) = (n+m)++$ is true.
For $n=(n++)$,
\begin{align*}
(n++) + (m++) &= ((n++)+m)++ &\text{From the definition of addition} \\
&=(n+(m++))++ \\
&=((n+m)++))++
\end{align*}
\end{proof}

Putting m = 0, we get $n+1 = n++$

\begin{prop}[Addition is commutative]
For any natural numbers $n$ and $m$, $n+m=m+n$
\end{prop}
\begin{proof}
We induct over $n$,
For the base case, $n=0$,

We must show that $m+0 = 0+m$
From the definition of addition, we have
$$0+m = m$$

As shown earlier, we have

$$m+0 = m$$

This is clearly true for $n=0$.

Now suppose inductively that $m+n = n+m$

For $n=n++$, we must show that $m+(n++) = (n++) + m$

We know from the definition of addition that,

$$(n++) + m := (m+n)++$$

And we proved earlier that,

$$m+(n++) = (m+n)++$$

Therefore,

$$m+(n++) = (n++)+m$$
\end{proof}
\begin{prop}[Addition is associative]
For any natural numbers, $a,b$ and $c$, we have $(a+b)+c = a+(b+c)$
\end{prop}
\begin{proof}
We take $(a+b)+n = a + (b+n)$

Inducting over n,

For $n=0$,

We have in the LHS,
\begin{align*}
&=(a+b)+0 &\text{Since $n+0 = n$}\\
&=a+b
\end{align*}

On the RHS,
\begin{align*}
&=a + (b+0) &\text{Since $n+0 = n$}\\
&=a + b
\end{align*}

Suppose inductively that $(a+b)+n = a+(b+n)$,

For $n=n++$,
We have to show that $(a+b)+(n++) = a+(b+(n++))$

On the LHS we have,

\begin{align*}
&=(a+b)+(n++) \\
&=(a+b+n)++ &\text{(From the lemma $m+(n++) = (m+n)++$)} \\
\end{align*}

On the RHS we have,

\begin{align*}
&=a+(b+(n++)) \\
&=a+(b+n)++ &\text{(From the lemma $m+(n++) = (m+n)++$)} \\
&=(a+b+n)++
\end{align*}

LHS = RHS
\end{proof}

\begin{prop}[Cancellation Law]
Let $a,b,c$ be natural numbers such that $a+b=a+c$. Then we have $b=c$.
\end{prop}
\begin{proof}
We have,
$$n+b=n+c$$

Inducting over n,
For the base case, $n=0$
\begin{align*}
0 + b &= 0 + c \\
b &= c
\end{align*}

Suppose inductively that $n+b=n+c$
For $n=n++$,
$$(n++)+b=(n++)+c$$
On the LHS
\begin{align*}
&=(n++) + b \\
&=(n+b)++
\end{align*}

On the RHS
\begin{align*}
&=(n++) + c \\
&=(n+c)++
\end{align*}

We know from the inductive hypothesis that,
$$\text{If} n+b = n+c, \text{then} b = c$$

Thus we have,
$$b++ = c++$$
\end{proof}

\begin{definition}[Positive natural number]
All numbers where,
\[
n \neq 0, n \in \mathbb{N}
\]
\end{definition}
\begin{prop}
If $a$ is a positive natural number and $b$ is a natural number, then $a+b$ is positive.
\end{prop}
\begin{proof}
Inducting over b,

For $b$ = 0,
\begin{align*}
a+0 = a
\end{align*}
This proves the base case, since we know a is positive.

Now, suppose inductively, that $(a+b)$ is positive.

For $(a+(n++))$,
\begin{align*}
a+(n++) = (a+n)++
\end{align*}
We know from Axiom 3 that $n++ \neq 0$. Thus we close the inductive loop.
\end{proof}
\begin{lemma}
For every $a$, there exists a unique $b$ such that $b++ = a$
\end{lemma}
\begin{proof}
Proof by contradiction,
Suppose that there are two different increments, $m++$, $n++$ that equal to $a$,

We have,
\begin{align*}
m++ &= a \\
n++ &= a
\end{align*}

Then we can say,
\begin{align*}
m++ &= n++ \\
m + 1 &= n+1 \\
m &= n &\text{(By Cancellation Law)}
\end{align*}

But we said that m and n are different numbers which increment to $a$.

Therefore, we can conclude that there is only one number $b$ which increments to $a$
\end{proof}
*** Order
\begin{definition}[Order]
Let n and m be natural numbers we say that $n$ is greater than or equal to m, and write $n \geq m$ iff we have $n = m + a$ for some natural number $a$. We say that $n > m$ when $n \geq m$ and $n \neq m$
\end{definition}
\begin{prop}[Basic properties of order for natural numbers]
Let $a,b,c$ be natural numbers then
\begin{enumerate}
\item (Order is reflexive) $a \geq a$
\item (Order is transitive) If $a \geq b$ and $b \geq c$, then $a \geq c$
\item (Order is antisymmetric) If $a \geq b$ and $b \geq a$ then $a=b$
\item (Addition preserves order) $a \geq b$ if and only if $a+c \geq b+c$
\item $a<b$ if and only if $a++ \leq b$
\item $a<b$ if and only if $b= a+d$ for some positive number d.
\end{enumerate}
\end{prop}
\begin{proof}
\begin{enumerate}
\item Proving order is reflexive, $a \geq a$

We know that,

$a = a + 0$

From the definition of order,
We can write that $a \geq b$ when $a = b + d$ where $d \in \mathbb{N}$

Thus $a \geq a$.

\item Proving order is transitive, $a \geq b$ and $b \geq c$ then $a \geq c$

We write,

\begin{align*}
a &= b + d \\
b &= c + e \\
a &= c + e + d
\end{align*}
We can say that since $(e+d) \in \mathbb{N}$

We define $f := (e+d)$
Where $f \in \mathbb{N}$
\begin{align*}
a &= c + (f)
\end{align*}

Thus we can say,
$$\text{If } a \geq b, b \geq c \text{ then } a \geq c$$

\item Proving order is antisymmetric, If $a \geq b$ and $b \geq a$ then $a=b$
We can say,
\begin{align*}
a = b + d \\
b = a + e \\
\end{align*}
Where $d,e \in \mathbb{N}$

\begin{align*}
a = (a + e) + d\\
b = (b + d) + e \\
\end{align*}

Then we can write,
\begin{align*}
a = a + (e + d)\\
b = b + (d + e) \\
\end{align*}

Then we can say that $(e+d)$ and $(d+e)$ are 0.

We know that if $a + b = 0$ then $a,b = 0$

Thus $d$ and $e$ are 0.
\begin{align*}
a = b + d \\
a = b
\end{align*}
\item Proving $a < b$ if and only if $b =a+d$ for some positive number d
If $b = a+d$ where $d$ is a positive natural number, $d \neq 0$

Which means that $b \neq a + 0$ or $b \neq a$

This means that b is strictly greater than a

If $a<b$ then $a \geq b$ and $a \neq b$

So if $a \geq b$
Then,
\begin{align*}
a = b + d \\
\end{align*}
But,
\begin{align*}
a \neq b \\
a \neq b + 0 \\
d \neq 0
\end{align*}
Thus d cannot be 0. $d$ can only be a positive natural number.
\item Proving addition preserves order, $a \geq b$ if and only if $a + c \geq b + c$
Proving $a \geq b$ if $a + c \geq b + C$

Where $d \in \mathbb{N}$
\begin{align*}
a + c &= b + c + d & &\text{By definition} \\
a + c &= (b+d) + c & \\
a &= (b+d) & &\text{By cancellation law}\\
a &\geq b
\end{align*}
Proving $a + c \geq b +c$ if $a \geq b$

We know,
\begin{align*}
a = b + d \\
\end{align*}
Where $d \in \mathbb{N}$

We write a+c using what we know from above,
\begin{align*}
a + c &= b + d + c \\
a + c &= b + c + d \\
(a + c) &= (b + c) + d \\
a + c &\geq b + c
\end{align*}

\item Proving $a < b$ if and only if $a++ \leq b$
Proving $a < b$ if $a++ \leq b$

We can write,
\begin{align*}
a++ &= b + d &\text{Where $d \in \mathbb{N}$} \\
a++ + d &= b  \\
a + (d++) &= b \\
\end{align*}
Since from Axiom 3, we know that 0 is not an increment of any natural number, $(d++ \neq 0)$
Therefore,
\begin{align*}
a &< b
\end{align*}

\end{enumerate}
\end{proof}
\begin{prop}[Trichotomy of order for natural numbers]
Let $a$ and $b$ be natural numbers. Then exactly one of the following statements is true: $a<b, a=b or a>b$
\end{prop}
\begin{proof}
First we show that no more than one of the statements is true.
If $a<b$ then $a \neq b$ by definition. If $a>b$ then $a \neq b$ by definition. If $a>b$ and $a<b$ then $a=b$, which we proved earlier.

Now to show that exactly one of these statements are true.
We induct on a,

When a = 0,
We know that,
\begin{align*}
&b &= 0 + b &(\forall b \in \mathbb{N})\\
&b &\geq 0
\end{align*}

Suppose inductively that exactly one of the above statements are true for a and b.
For a++,
We take each statement. First for $a>b$
\begin{align*}
a &> b \\
a &= b + d \\
(a++) &= (b + d)++ \\
(a++) &= b + d++ \\
(a++) &> b &\text{If $d \in \mathbb{N}$ then $d++ \in \mathbb{N}$}
\end{align*}
For $a=b$
\begin{align*}
a &= b \\
(a++) &= (b)++ \\
(a++) &= b + 1 \\
a &> b \\
\end{align*}
For $a<b$
\begin{align*}
a &<b\\
a + d = b \\
(a + d)++ = b++ \\
(a++) + d = b++ \\
(a++) + d = b + 1 \\
\end{align*}
We have two cases,
If $d = 1$,
Then by cancellation law
$$ a++ = b $$
If $d \neq 1$
Then
$$a++ < b$$
But never both, which concludes the inductive loop.
\end{proof}
*** Special Forms Of Induction
\begin{prop}[Strong Principle Of Induction]
Let $m_0$ be a natural number, and let $P(m)$ be a property pertaining to an arbitrary natural number $m$. Suppose that for each $m \geq m_0$, we have the following implication: if $P(m')$ is true for all natural numbers $m_0 \leq m' < m$, then $P(m)$ is also true.(In particular this means that $P(m_0$ is true, since in this case the hypothesis is vacuous.) Then we can conclude that $P(m)$ is true for all natural numbers $m \geq m_0$.
\end{prop}
\begin{proof}
For a property $Q(n)$, which is the property that $P(m')$ is true for $m_0 \leq m < n$, then $P(n)$ is true... Then it is true $\forall m \geq m_0$

For $Q(0)$, we can say that the statement is vacuous since the conditions are not satisfied for both when $m_{0} = 0$ and when $m_{0} <0$

Suppose inductively that $Q(n)$ is true.
Which means that

Then for Q(n++)
\end{proof}
\begin{prop}[Backward Induction]
Let $n$ be a natural number, and let $P(m)$ be a property pertaining to the natural numbers such that whenever $P(m++)$ is true, then $P(m)$. Suppose that $P(n)$ is also true. Prove that $P(m)$ is true for all natural numbers $m \leq n$.
\end{prop}
\begin{prop}[Induction starting from the base case $n$]
Let n be a natural number, and let $P(m)$ be a property pertaining to the natural numbers such that whenever P(m) is true, P(m++) is true. Show that if P(n) is true, then P(m) is true for all m ≥ n. (This principle is sometimes referred to as the principle of induction starting from the base case n.)
\end{prop}
#+BEGIN_proof
Take a property $P(n)$, $m \geq n$

Inducting over $n$,
#+END_proof
*** Multiplication
\begin{definition}[Multiplication]
Let $m$ be a natural number. To multiply zero to $m$, we define $0 \times m := 0$. Now suppose inductively that we have defined how to multiply $n$ to $m$. Then we can multiply $n++$ to $m$ by defining $(n++) \times m := (n \times m) + m$
\end{definition}
We can say $0 \times m = 0$, $1 \times m = 0 + m$, $2 \times m= 0 + m + m$ and so on.
\begin{lemma}
Prove that multiplication is commutative
\end{lemma}

For simplicity we now write $a \times b$ as $ab$

*** Exercise
**** Prove the identity $(a+b)^2 = a^2 + 2ab + b^2$
**** (Euclid's division lemma)
**** Backward Induction
$m \in \mathbb{N}, P(m), P(m++) \implies P(m)$, Suppose $P(n)$ is true, then $P(m) \forall m \le n$
For the base case, n = 0,
P(0) \implies P(0), so it's true.

For the inductive step, supposing $Q(n)$ is true,
**** Strong induction
**** Distributive Law
**** Multiplication
***** Cancellation Law
***** Associativity
***** If a<b, and c is positive then ac<bc
