j+title: Mahabharata

* Mahabharata A Brief Summary
** Narrations
- During the Sarpa satra(sacrifice of snakes), Vaisampayana narrates it to King Janamajeya
- Lomaharsana re-narrates it completeley and classifies into 18 parvas
** Miscellaneous
- Bharata comes from the name of Bharata, who is the son of Shakuntala and Dusyanta, he is the common ancestor of the Kauravas and Pandavas.
** 18 Parvas
*** Adi Parva
- Story of Bharata
**** Bhishma
son of King Santanu and Ganga Devi. Devavrata vows to never marry and observes chastity so that father could marry Satyavati. He becomes Bhishma(one who undertook a terrible vow), now he can only die when he wishes to (boon from father.)


He abducts Kasi princesses Amba, Ambika and Ambalika at a function as brides for [[Vichitravirya]]
**** Chitraganda
son of King Santanu and Satyavati, dies at the hands of a Gandharva in a fierce battle
**** Vichitravirya
son of King Santanu and Satyavati. He dies too young to have children.
**** Veda Vyasa
stepbrother to Bhishma, through his grace Dhritarashra, Pandu and Vidura are born.

Niyoga - socially acceptable cuckoldry

Intervenes when Gandhari punches her stomach, takes the lump of flesh and divides the flesh into 101 equal parts, keeps them inside mud pots. 100 Kaurava brothers and one sister.
**** Dhritarashtra
born blind. Marries Gandhari
**** Gandhari
Daughter of Gandhara king, Subala. Ties a cloth around her eyes to match Dhritarashtra. When Yudisthira is born, beats her stomach, gives birth to 101 children.
**** Drona
Drona and Drupada were childhood friends. Drona visits Drupada asking for money, Drupada was like "hell nah bruh i ain't got broke friends"

He then becomes the chief weaponry tutor of all the princes. He demands Guru dakshina, which is Drupada being captured. Kauravas fail and the Pandavas succeed cause of course they do. Drona takes his kingdom and gives it back to Drupada and says, we're equal now. Drupada gets understandably angry at this and makes a big sacrifice, Dristadyumna and Draupadi are born.
**** Pandu
Pale-complexioned. Marries Kunti and Madri
**** Kunti
Obtains a mantra from Maharishi Durvasa and gives birth to these children,
- Karna - Surya Deva... puts him in a box and sets him afloat
- [[Yudisthira]] - Yamadharma Deva
- [[Bhima]] - Vayu
- [[Arjuna]] - Indra

After Pandu's death, Kunti returns to the kingdom
**** Madri
- Nakula, Sahadeva - Ashwini Devas
**** Pandavas
They grow up with the Kauravas, escape the wax palace burning plot from [[Duryodhana]] with the help of Vidura. Arjuna disguised as a brahmin shoots down a moving target and wins over Draupadi. They also Rakshasas like Baka and Hidimba

Krishna is like ayo Kauravas, "what you did was messed up give em half the kingdom pretty please?". Dhritarashtra is like, '"yo fair here ya go". Pandavas call it Indraprastha
**** Draupadi
Draupadi marries all 5 Pandavas.
*** Sabha Parva
**** Yudisthira
Bets all his siblings himself and his wife Draupadi, gets set free from the Draupadi boon. Duryodhana calls him again to another gamble and bro said, "Say less". They have to give up their kingdom and stay in the forest for 12 years and 1 year in disguise

**** Bhima
Takes oath to pierce the chest of Duhsasana and break the thighs of Duryodhana
**** Draupadi
Draupadi gets dragged into court and disrobed, prays to Krishna and activates her infinite cloth glitch

She gets boons from Dhritarashra and uses that to set the pandavas free of the bet.
**** Duhsasana
Duhsasana drags Draupadi into court and tries to disrobe her
*** Aranya Parva
jTHey kill evil beings, earn divine weapons like Pasupatastra
*** Virata Parva.
Last year of exile

Duryodhana refuses to give back the kingdom and war happens
**** Abhimanyu
Son of Arjuna and Subhadra. Gets married to daughter of King Virata
**** King Virata
Gives the Pandavas shelter in the last year of exile
*** Udyoga Parva
**** Krishna
Krishna tries to stop the war by negotiating on  both sides. Duryodhana says no, bro gets pissed and mogs him with his true form(Viswarupa). He becomes Arjuna's charioteer
**** Duryodhana
Hears Krishna out and says... nah.

Krishna's army goes to him(Yadava Sena)
*** Bhishma Parva
The first 10 days of war is known as the Bhishma Parva. Let army count be Akshauhini - 21870 * (3 horses for 1 chariot, 1 elephant, 5 soldiers)
**** Bhishma
Leads the Kaurava Army
**** Arjuna
Gets into an existential crisis, Krishna is like "chill out, do your dharma" and plugs his self-published philosophy book.

He takes out his Gandiva(his bow)
**** Drishtadyumna
Leads the Pandavas
*** Drona Parva
**** Drona
Gets appointed as Commander of Kaurava army
**** People who died
Iravan - 8th
Abhimanyu - 13th
Drupada, Ghatotkaca, Drona, Bhagadatta, Bhurisravas, Jayadratha - 14th
*** Karna Parva
**** Karna
Gets appointed as Commander of Kaurava army, gets unalived by Arjuna
**** Salya
Charioteer of Karna, tells Karna not to kill Arjuna telling him "You're not Him bro, here's a story about a swan and crow"
*** Salya Parva
**** King Of Madri
Gets appointed as Commander of Kaurava army, gets unalived by Arjuna
**** Salya
Dies at the hands of Yudisthira
**** Balarama
Couldn't bear to watch the fight of his two students, he takes a pilgrimage along the Sarasvati river
**** Duryodhana
He's immortal cause Gandhari looked at him, his thighs were covered tho, Bhima commits a foul
*** Souptika Parva
**** Motivations
Kritavarma , Kripa and son of Drona (Asvatthama) came to the battlefield and saw Duryodhana on the ground.

Asvatthama vowed to not take off his armour without killing the pandavas and allies. Asvatthama killed Dristadyumna
*** Stri Parva
**** Gandhari
The and otherw wives see all the warriors lying dead, decide to perform last rites
*** Shanti Parva
**** Yudhishtira
talks about his remorse after the war
**** Bhishma
laying on the bed of arrows, he preaches to Yudhishtira about Dharma, Artha and administering a kingdom
and goes to heaven
*** Anushasana Parva
Bhishma's teachings to Yudisthira
*** Ashwamedhika Parva
**** Yudhishtira
after the war, decides to conduct the Ashwamedha Yagna to reaffirm his authority
**** Parikshit
birth is described
son of abhimanyu, captures the Ashwamedha horse eventually
**** Arjuna
his journey with the ashwamedha horse, battling many kings along the way is detailed
*** Ashramavasika Parva
**** Dhritarashtra
retires to the forest and becomes an ascetic with Gandhari and Vidura
