#+TITLE: Modelling, Simulation And Analysis Notes
#+AUTHOR: Adithya Nair
#+LATEX_HEADER: \input{preamble}
#+LATEX_HEADER: \usepackage{bondgraphs}
#+LATEX_CLASS: report
#+EXPORT_FILE_NAME: exports/modelling, simulation and analysis.pdf

* Notes
** Course Overview
1. Introduction to Modelling
2. Bond graph modelling
3. Basic System Models

The textbooks to be followed is: "System Dynamics - Modeling, Simulation And Control Systems", "Modern Control Engineering, Katsuhiko Ogata"

What is modelling? It's a mathematical representation of a system. These representations allow us to evaluate the results of that given system. This course is focused on equipping us with the working knowledge to develop such mathematical models for our systems.

Upon modelling the system, we can start controlling this system. With the equations we have made, we can now add our own inputs to those equations. This in a nutshell is what the course is about.

** Unit 1
*** What Is Modelling?
 - Model - Models of the systems are simplified, abstracted constructs used to predict their behaviour.
 - Mathematical Modelling - Predicts only a certain aspect of the behaviour
*** Uses Of Modelling
Modelling consists of input variables $U$, which performs certain operations on a dynamic system $S$, with state variables $X$ to give some output variables $U$.
Analysis means that given an input for the present, and the system itself.

We can predict the outputs for the future. To exert some form of control, the system $S$ are used. Another term used is identification, identification means that you already $U$, and $Y$. We know the inputs and the outputs, and we map $U$ to $Y$ with the system $S$. We *identify* the system that would map the inputs to the outputs. This is done by experimenting and figuring out what mapping works best to generate the outputs from the inputs. The way to tell whether a model is good is to see if it is consistent with large sets of input and outputs.
*** Types Of Modeling
Principle of superposition - it means that there's a linear correlation of the inputs to the outputs.
|----------------+------------------------------------------------------------+--------------------------------------------------------|
| Type Of System | Description                                                | Differential Equations                                 |
|----------------+------------------------------------------------------------+--------------------------------------------------------|
| Linear         | Principle of superposition applies                         | Linear differential equations.                         |
| Distributed    | Dependent variables are functions of space and time        | Partial differential equations                         |
| Lumped         | Dependent variables are independent of spatial coordinates | Ordinary differential equations                        |
| Time - varying | Model parameters vary in time                              | Differential equations with time-varying coefficients. |
| Stationary     | Model parameters are constant in time                      | Differential equations with constant coefficients      |
| Continuous     | Dependent variables over continuous range                  | Differential equations                                 |
| Discrete       | dependent variables defined only for distinct values       | Time-difference equations                              |
|----------------+------------------------------------------------------------+--------------------------------------------------------|


| Name    | Age |
| Adithya |  12 |
| Anil    |  14 |

*** System Nomenclature
#+begin_definition :options [Dynamical System]
	A Dynamical system is a particle or ensemble of particles whose state varies over time and thus obeys differential equations involving time derivatives.
#+end_definition
#+begin_definition options
The state of a Dynamic system is the smallest set of variables(called state variables) such that the knowledge of these variables at $t=t_0$, together with the knowledge of the input for $t\geq t_0$, completely determines the behaviour of the system for any time $t \ge t_0$. The number of state variables is the same as the number of inital conditions needed to completely solve the system models
#+end_definition
#+begin_definition options
If n state variables are needed to completely describe the behaviour of a given system, then the $n$ state variables can be considered the components of a vector $X$. Such a vector is called a state vector.
#+end_definition

#+begin_definition options
The state space is the  $n$ -dimensional space whose coordinate axes consist of the $x_1$ axis, $x_2 axis$ where $x_1, \cdots , x_n$
#+end_definition

Suppose you started observing your model at point $t_0$. You can read any point in the state space and immediately figure out exactly how the system was behaving at any given point.


Input Variables: $U_{n\times1} = [U_1, U_2, \cdots, U_r]^T$
State Variables: $X_{n\times1} = [X_1, X_2, \cdots, X_r]^T$
Output Variables: $Y_{n\times1} = [Y_1, Y_2, \cdots, Y_r]^T$

We can write the derivatives of the state variables as functions of the inputs and the state variables and time.

We can then write these functions as one vector.

\[
\dot{X}(t) = F(U,x,t)
\]

We can similarly write the derivatives of the outputs as functions of the inputs and state variables.

\[
\dot{Y}(t) = G(U,X,t)
\]
We write the states' derivative as a linear combination, which can then be written as a matrix.

$$ \dot{X}(t) = \begin{bmatrix} a_{11} & a_{21} & \cdots & a_{1n} \\ \vdots & \ddots & & \vdots \\ a_{n1} & a_{n1} & \cdots & a_{nn} \\ \end{bmatrix} \begin{bmatrix} x_1 \\ \vdots \\ x_n \end{bmatrix} \begin{bmatrix} b_{11} & b_{21} & \cdots & b_{1n} \\ \vdots & \ddots & & \vdots \\ b_{n1} & b_{n1} & \cdots & b_{nn} \\ \end{bmatrix} \begin{bmatrix} u_1 \\ \vdots \\ u_n \end{bmatrix}$$
We get the equation,

$$\dot{X}(t) = A_{n \times n} X_{n \times 1} + B_{n \times r} U_{r \times 1}$$

A is the `state' matrix, and B is the `input' matrix

Similarly we can write,
$$\dot{Y}(t) = C_{m \times n}X_{n \times 1} + D_{m \times r}U_{r \times 1}$$

We apply the Laplace transform to convert integrals and derivatives into algebraic operations.


$$U(t) \rightarrow G(s) \rightarrow Y(t)$$
We get the transfer function $G(s)$ by the formula
$$G(s) = \frac{Y(s)}{U(s)}$$

So we can get our outputs, by

$$Y(s) = G(s)U(s)$$
#+begin_definition options
A block diagram of a system is a pictorial representation of the functions performed by each component and of the flow of signals. Such a diagram depicts the interrelationships that exist among the various components. Differing from a purely abstract mathematical representation, a block diagram has the advantage of indicating more realistically the signal flows of the actual system.
#+end_definition

*** Modeling Of Dynamical Systems.
Consider the system shown in the figure. The main body of mass M is propelled along a horizontal track by a traction force $f$. The main body contains an actuator for rotating the pendulum. The  actuator applies a torque T to the arm. The pendulum has a total mass $m$ and a moment of inertia $I$ relative to its mass center at point C.
[[pdf:~/University-Latex-Notes/Modelling, Simulation And Analysis/textbooks/Katsuhiko Ogata - Modern Control Engineering-Prentice Hal (2010).pdf::78++0.00][Katsuhiko Ogata - Modern Control Engineering-Prentice Hal (2010).pdf: Page 78 Systems example]]

*** Bond Graph Modelling
What we did earlier is a classical approach to modelling. We find  the differential equations and generate matrix equations with inputs, state variables and output.

What we do here is,
\begin{align*}
\text{Physical} &\text{System} \\
&\downarrow \\
\text{Engineering} &\text{Model} \\
&\downarrow \\
\text{Bond} &\text{Graphs} \\
&\downarrow \\
\text{Software generated} &\text{differential equations} \\
&\downarrow \\
\text{Simulation} &\text{Language} \\
&\downarrow \\
\text{Out}&\text{put}
\end{align*}

*** Generalizd Variables
- Power Variables
 - Effort $e(t)$
 - Flow $f(t)$
Power = $e(t) \times f(t)$
- Energy variables
  - Momentum $p(t)$
  - Displacement $q(t)$
$p(t) = \int e(t) dt$
$q(t) = \int f(t) dt$

|----------------+--------------------+------------------|
|                | Effort             | Flow             |
|----------------+--------------------+------------------|
| Electrical     | Voltage            | Current          |
| Translational  | Force              | Velocity         |
| Rotational     | Torque             | Angular velocity |
| Hydraulic      | Pressure           | Volumetric Flow  |
| Chemical       | Chemical Potential | Molar Flow       |
| Thermodynamics | Temperature        | Entropy Flow     |
|----------------+--------------------+------------------|

**** Bond Graphs
A bond graph is a labelled directed graph, each link has an assigned orientation.

**** Multiports
Places at which subsystems can be interconnected, power can flow through ports between subsystems.

#+begin_src octave
global m b k;
m = 1;
b =  1; %Damping constant
k = 1; % Spring constant

tspan = [0 10];
IC = [0 0];

[time, X_state] = ode45(@f,tspan , IC);

function x_dot = f(t,X)
  global m b k
  u = sin(t);
  x_dot = [X(2);-(b/m)*X(2) - (k/m)*X(1) + (u/m)];
end
figure('units', 'normalized', 'outerposition', [0 0 1 1])
subplot(2,2,1)
grid on;
xlabel('Time(s)')
ylabel('Displacement')
plot(time, X_state(:,1))

subplot(2,2,3)
grid on;
xlabel('Time(s)')
ylabel('Velocity')
plot(time, X_state(:,2))


subplot(2,2,[2 4])
grid on;
xlabel('Displacement(m)')
ylabel('Velocity(m/s)')
plot(X_state(:,1), X_state(:,2))
s output
#+end_src


REFERENCE
[[https://ocw.mit.edu/courses/2-141-modeling-and-simulation-of-dynamic-systems-fall-2006/71ca8916669d0aa6839ce780db9f5288_bond_graph_intro.pdf][MIT COURSE NOTES ON BOND GRAPH MODELLING]]
** Unit 2
*** Transformers
We have bond graphs now, and we can say certain things about the efforts and flows using bond graphs.


What we can do next is write functions known as transformers that convert the input effort into the output effort, or the input flow into the output flow, based on the causal stroke.
*** Gyrators
What we can do with gyrators convert the input of one form into the output of another form, based on the causal stroke.
* Assignments
[[file:~/University-Latex-Notes/Modelling, Simulation And Analysis/assignments/23AID201_MSA_PracticeSheet01.pdf][Practice Sheet 01]]
1. For mathematical modelling, formulation of state space equation from a mathematic model, and block diagram representation follow [[file:~/University-Latex-Notes/Modelling, Simulation And Analysis/textbooks/Modern Control Engineering 5th Edition.pdf][Modern Control Engineering by Ogata]] - [[pdf:~/University-Latex-Notes/Modelling, Simulation And Analysis/textbooks/Modern Control Engineering 5th Edition.pdf::24++0.00][Chapter 2]] [[pdf:~/University-Latex-Notes/Modelling, Simulation And Analysis/textbooks/Modern Control Engineering 5th Edition.pdf::40++0.00][section 2.4]] and [[pdf:~/University-Latex-Notes/Modelling, Simulation And Analysis/textbooks/Modern Control Engineering 5th Edition.pdf::74++0.00][Chapter 3(section 3.1 - 3.3)]]

2. For bond graph modelling, refer System Dynamics Book by Dean C Karnopp Chapter 2 and Chapter 3, section 3.3, 3.4
* Project Notes
 * Simscape, or a matlab simulink model
 * Provision is made for solidworks CAD models.
