#+title: Introduction To Robotics
#+author: Adithya Nair
#+LATEX_HEADER: \input{preamble}
#+LATEX_CLASS: report
* Robotics
** Unit 1
*** Introduction
This course is mainly going to focus on *Manipulators*. These machines are used to manipulate positions and the state of the objects in an environment. We're going to break down their movements into Dynamics Analysis akin to the work done in Computational Mechanics.
*** Syllabus
- Overview Of Robotics
- Kinematics Of Simple Robotic Systems
- Dynamics And Control Of Simple Robotic Systems
*** Glossary
1. Actuator - Does work upon receiving voltage
2. Encoder - Sensor that measures raw angle data.


Software for robotics - *v-rep*, MATLAB
This software involves making a CAD model, and apply a mathematical model. Unity can also be used in making such models.

*** Degree Of Freedom
The degree of  freedom of a mechanical system is defined as the no. of independent paramets need to completely define its position in space at a given time..

The degree of freedom is defined with respect to a reference frame. If the object is free to rotate and move, it means it has 6 degrees of freedom.
Localization - Finding the position and orientation of an object in 3-dimensional space.

We call a system 'fully actuated' when there are as many actuators as there are degrees of freedom.
$$\text{No. of controlling inputs} < \text{No. of degrees of freedom}$$
Underactuated systems contain lesser actuators than the number of degrees of freedom
$$\text{No. of controlling inputs} = \text{No. of degrees of freedom}$$

Redundant systems contain more actuators than the number of degrees of freedom
$$\text{No. of controlling inputs} >\text{ No. of degrees of freedom}$$

*** Kinematic Pair
Linkages are the basic elements of all mechanisms and robots. Links are rigid body member with nodes, and joints are connection between links at nodes. Allows relative motion between links.
*** Robotic Manipulator
- Why study kinematics and dynamics of robotic manipulator
  - To manipulate an object in space
  - Understand the workspace and limitations of a robotic manipulator
  - Understand and estimate contact force between end-effector and object being manipulated.

*** Pose of a rigid body
A rigid body is completely defined in space by its position and orientation with respect to a reference.

We use the terminology `Inertial reference frame' to mean an observer where Newton's laws of physics apply. We use the terminology 'Inertial reference frame' to mean an observer where Newton's laws of physics apply and the frame itself does not accelerate. Generally the base of the robotic manipulator is treated as the inertial reference frame

We use unit vectors $\hat{x},\hat{y},\hat{z}$ to describe the basis vectors. For the orientation of the rigid body, since they lie in 3d space, we must define new basis vectors to define the orientation, $\hat{x'}, \hat{y'}, \hat{z'}$

$$
\hat{x'} = x'_x \hat{x} + x'_y\hat{y} + x'_z\hat{z}
$$

$$
\hat{y'} = y'_x \hat{x} + y'_y\hat{y} + y'_z\hat{z}
$$

$$
\hat{z'} = z'_x \hat{x} + z'_y\hat{y} + z'_z\hat{z}
$$


**** When the frame is translationally different from the original frame.
$$
\vec{^AP} = \vec{^BP} + \vec{^AP}_{B org}
$$
Where $^A\vec{P}$ is the position vector of P with respect to A, $\vec{^BP}$ is the position vector of P with respect to B, and $\vec{^AP}_{B org}$ is the vector of A to B.
**** When the frame is oriented differently from the original frame.
Generating a rotation matrix $^B_AR$ to rotate vectors from a frame B to A. Where A and B are reference frames, with B being oriented differently than A.

$$ \begin{bmatrix} \hat{X_b} \cdot \hat{X_a} & \hat{Y_b} \cdot \hat{X_a} & \hat{Z_b} \cdot \hat{X_a} \\ \hat{X_b} \cdot \hat{Y_a} & \hat{Y_b} \cdot \hat{Y_a} & \hat{Z_b} \cdot \hat{Y_a} \\ \hat{X_b} \cdot \hat{Z_a} & \hat{Y_b} \cdot \hat{Z_a} & \hat{Z_b} \cdot \hat{Z_a} \\ \end{bmatrix}$$

We can simply the matrix into 3 column vectors, with the notation $^AX_B$ which means B with respect to A

$$\begin{bmatrix}\hat{^AX_B} & \hat{^AY_b} & \hat{^AZ_B}\end{bmatrix}$$
**** When the frame is both translationally and oriented different from the original frame
$$ ^A\vec{P} = ^A_B R ^B\vec{P} + ^A\vec{P}_{B org}$$
To simplify the equations, we write.

$$^A\vec{P} = _B^AT ^BP$$
Where T becomes
$$^A_BT = \begin{bmatrix}^A_BR_{3 \times 3} & ^AP_{B org} \\ 0_{1 \times 3} & 1_{1 \times 1}\end{bmatrix}$$

This T is the homogeneous transformation matrix.

The Rotation Matrix belongs to a category of matrices called $SO(3)$(Special Orthogonal Matrices)
*** Denavit Hartenberg Parameters
These parameters are used to assign the same co-ordinate frames while dealing with robotic manipulators to ensure that the entire scientific community are working under the same conventions.
- Number the link sequentially from $0$ to $n$. Giving us $n+1$ links.
- Number the joints sequentially from $1$ to $n$, Giving us $n$ joints.
- Number of co-ordinate frames: $n+1$
- The $Z_i$ axis is aligned with the $(i+1)^th$ joint axis.
- $X_i$ is defined along the common normal between the $Z_i$ and $Z_{i-1}$ axis.(Common normal is the line which is perpendicular to both of these axes.)
- $Y_i$ is obtained via cross product between $Z_i$ and $X_i$ axis.
- The origin is placed at this point of intersection of $x_i$, $y_i$ and $z_i$
- We define $H_i$(which is the point of intersection of the common normal of the next axis with the current axis.), and 4 new terms:
  - $a_i$ - Offset distance between two adjacent joint axes(The distance between $O_i$ and $H_{i-1}$)
  - $d_i$ - Distance between $H_{i-1}$ and $O_{i-1}$
  - $\alpha_i$ Angle between $Z_i$ and $Z_{i-1}$ when viewed from $X_i$, this is also known as the twist angle.
  - $\theta_i$ Angle between $X_i$ and $X_{i-1}$ when viewed from $Z_i$,

For a 3R Planar serial chain manipulator:

|-------------+-----+-----+---------+-----|
|             | a_i | d_i | $\alpha_{i}$ | \theta_i |
|-------------+-----+-----+---------+-----|
| Joint i = 1 | L_1 |   0 |       0 | \theta_1 |
| Joint i = 2 | L_2 |   0 |       0 | \theta_2 |
| Joint i = 3 | L_3 |   0 |       0 | \theta_3 |
|-------------+-----+-----+---------+-----|
*** Rotation Matrix
We have three reference frames, with a common origin. With the notation we have setup we can say, $\{0\},\{1\},\{2\}$ can be defined for a point $P$

\begin{align*}
^0P = ^0_1R ^1P \\
^0P = ^0_2R ^2P \\
^1P = ^1_2R ^2P \\
^0_2R = ^0_1R _2^1R
\end{align*}
*** Derivation Using DH Parameters
These 4 parameters can be expressed by,

$$^{i-1}A_i = T(z,d)T(z,\Theta),T(x, \alpha), T(x, a)$$
*** Skew Symmetric Matrix

A matrix such that $A = -A^T$

So this means that,

$$S + S^{T}=0$$

$$\vec{a} = a_x \hat{i} + \vec{a_y} \hat{j} \vec{a_z} \hat{k}$$

We define a matrix function,

$$S(\vec{a}) = \begin{bmatrix}
0 & -a_z & a_y \\
a_z & 0 & - a_x \\
-a_y & a_x 0
\end{bmatrix}
$$

So we can say for the basis vectors

$$S(\hat{i}) = \begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & -1 \\
0 & 1 & 0
\end{bmatrix}
$$
$$S(\hat{j}) = \begin{bmatrix}
0 & 0 & 1 \\
0 & 0 & 0 \\
-1 & 0 & 0dt&i0
\end{bmatrix}
$$
$$S(\hat{k}) = \begin{bmatrix}
0 & -1 & 0 \\
1 & 0 & 0  \\
0 & 0 & 0
\end{bmatrix}
$$

Multiplying the matrix function's output with a vector is the same as doing a cross product with those two vectors.
$$S (\vec{a}) P = \vec{a} \times \vec{p} $$
This matrix operation also has linearity in operations.
$$S (\alpha\vec{a} + \beta \vec{b}) P = \alpha S(\vec{a}) +  \beta S(\vec{b}) $$
When multiplied with a rotation matrix.
$$^a_bR S(\vec{a})^a_bR^T = S(^a_bR \vec{a})$$

We know that,
\begin{align*}
R R^T &= I \\
R(\theta) R^t(\theta) &= I \\
\text{Taking the derivative} \\
\frac{d R(\theta)}{d \theta} R^T(\theta) + R(\theta) \frac{d R^{T}(\theta)}{d \theta} &= 0 \\
\frac{d R(\theta)}{d \theta} R^T(\theta) + R(\theta) \left( \frac{d R^{T}(\theta)}{d \theta} \right)^{T}&= 0 \\
\end{align*}

What this means is that the term $\frac{d R(\theta)}{d \theta} R^T (\theta)$ is a skew-symmetric matrix.

This means that the the term can be written as $S$,

$$S = \frac{d R(\theta)}{d \theta} R^T (\theta)$$

In other words, S becomes an operator on $R$ to give us the derivative.

$$S(\hat{k})R(\theta) = \frac{d R(\theta)}{d\theta}$$

Taking both sides with respect to time,

$$ \frac{d R(\theta)}{d \theta} \frac{d \theta}{dt} = \dot{\theta} S(\hat{k})R(\theta) $$
In other words,
$$\dot{R} = S(\dot{\theta}\hat{k})R(\theta)$$

So we have,
$$\dot{R} = S(\vec{\omega})R(\theta)$$

$$S(\vec{\omega}) = \begin{bmatrix}
0 & -\omega_z & \omega_y \\
\omega_z & 0 & -\omega_x \\
\omega_y & \omega_{x} & 0
\end{bmatrix}$$

$$\Omega = \begin{bmatrix}
0 & -\omega_z & \omega_y \\
\omega_z & 0 & -\omega_x \\
\omega_y & \omega_{x} & 0
\end{bmatrix}$$

\begin{align*}
^0P = ^0_1R ^1P \\
^0P = R ^1P \\
^0 \dot{P} = \dot{R} ^1P + R^1 \dot{P} \\
^0 \dot{P} = S(\vec{\omega}) R ^1P \\
^0 \dot{P} = \omega \times R ^1 \vec{p} \\
^0 \dot{P} = \omega \times R ^1 \vec{p} \\
\vec{v} = \vec{\omega} \times \vec{r}
\end{align*}

** Unit 2 - Kinematics Of Robotic Manipulators
*** Forward And Inverse Kinematics
Forward kinematics is the use of the joint space to get to the task space.
Inverse Kinematics is the use of the task space to get to the joint space.

Workspace - The space of all points that the end effector can reach.
* Practice Sheets
[[file:~/university-notes/Introduction To Robotics/assignments/23AID202_ITR_PracticeSheet01.pdf][Practice Sheet 1]]
The notations used in our lectures are similar with this book.

- For Rotation Matrices, Pose of a rigid body, Euler Angles, Homogeneous Transformation ---> read Chapter 2
- For DH Parameters and Coordinate Convention ---> read Chapter 3, Sections 3.1 to 3.4
