#+title: Introduction To Robotics
#+author: Adithya Nair
#+LATEX_HEADER: \input{preamble}
#+LATEX_CLASS: report
* Robotics
** Unit 1
*** Introduction
This course is mainly going to focus on *Manipulators*. These machines are used to manipulate positions and the state of the objects in an environment. We're going to break down their movements into Dynamics Analysis akin to the work done in Computational Mechanics.
*** Syllabus
- Overview Of Robotics
- Kinematics Of Simple Robotic Systems
- Dynamics And Control Of Simple Robotic Systems
*** Glossary
1. Actuator - Does work upon receiving voltage
2. Encoder - Sensor that measures raw angle data.


Software for robotics - *v-rep*, MATLAB
This software involves making a CAD model, and apply a mathematical model. Unity can also be used in making such models.

*** Degree Of Freedom
The degree of  freedom of a mechanical system is defined as the no. of independent paramets need to completely define its position in space at a given time..

The degree of freedom is defined with respect to a reference frame. If the object is free to rotate and move, it means it has 6 degrees of freedom.
Localization - Finding the position and orientation of an object in 3-dimensional space.

We call a system 'fully actuated' when there are as many actuators as there are degrees of freedom.
$$\text{No. of controlling inputs} < \text{No. of degrees of freedom}$$
Underactuated systems contain lesser actuators than the number of degrees of freedom
$$\text{No. of controlling inputs} = \text{No. of degrees of freedom}$$

Redundant systems contain more actuators than the number of degrees of freedom
$$\text{No. of controlling inputs} >\text{ No. of degrees of freedom}$$

*** Kinematic Pair
Linkages are the basic elements of all mechanisms and robots. Links are rigid body member with nodes, and joints are connection between links at nodes. Allows relative motion between links.
*** Robotic Manipulator
- Why study kinematics and dynamics of robotic manipulator
  - To manipulate an object in space
  - Understand the workspace and limitations of a robotic manipulator
  - Understand and estimate contact force between end-effector and object being manipulated.

*** Pose of a rigid body
A rigid body is completely defined in space by its position and orientation with respect to a reference.

We use the terminology `Inertial reference frame' to mean an observer where Newton's laws of physics apply. We use the terminology 'Inertial reference frame' to mean an observer where Newton's laws of physics apply and the frame itself does not accelerate. Generally the base of the robotic manipulator is treated as the inertial reference frame

We use unit vectors $\hat{x},\hat{y},\hat{z}$ to describe the basis vectors. For the orientation of the rigid body, since they lie in 3d space, we must define new basis vectors to define the orientation, $\hat{x'}, \hat{y'}, \hat{z'}$

$$
\hat{x'} = x'_x \hat{x} + x'_y\hat{y} + x'_z\hat{z}
$$

$$
\hat{y'} = y'_x \hat{x} + y'_y\hat{y} + y'_z\hat{z}
$$

$$
\hat{z'} = z'_x \hat{x} + z'_y\hat{y} + z'_z\hat{z}
$$


**** When the frame is translationally different from the original frame.
$$
\vec{^AP} = \vec{^BP} + \vec{^AP}_{B org}
$$
Where $^A\vec{P}$ is the position vector of P with respect to A, $\vec{^BP}$ is the position vector of P with respect to B, and $\vec{^AP}_{B org}$ is the vector of A to B.
**** When the frame is oriented differently from the original frame.
Generating a rotation matrix $^B_AR$ to rotate vectors from a frame B to A. Where A and B are reference frames, with B being oriented differently than A.

$$ \begin{bmatrix} \hat{X_b} \cdot \hat{X_a} & \hat{Y_b} \cdot \hat{X_a} & \hat{Z_b} \cdot \hat{X_a} \\ \hat{X_b} \cdot \hat{Y_a} & \hat{Y_b} \cdot \hat{Y_a} & \hat{Z_b} \cdot \hat{Y_a} \\ \hat{X_b} \cdot \hat{Z_a} & \hat{Y_b} \cdot \hat{Z_a} & \hat{Z_b} \cdot \hat{Z_a} \\ \end{bmatrix}$$

We can simply the matrix into 3 column vectors, with the notation $^AX_B$ which means B with respect to A

$$\begin{bmatrix}\hat{^AX_B} & \hat{^AY_b} & \hat{^AZ_B}\end{bmatrix}$$
**** When the frame is both translationally and oriented different from the original frame
$$ ^A\vec{P} = ^A_B R ^B\vec{P} + ^A\vec{P}_{B org}$$
To simplify the equations, we write.

$$^A\vec{P} = _B^AT ^BP$$
Where T becomes
$$^A_BT = \begin{bmatrix}^A_BR_{3 \times 3} & ^AP_{B org} \\ 0_{1 \times 3} 1_{1 \times 1}\end{bmatrix}$$

This T is the homogeneous transformation matrix.

The Rotation Matrix belongs to a category of matrices called $SO(3)$(Special Orthogonal Matrices)
*** Denavit Hartenberg Parameters
These parameters are used to assign the same co-ordinate frames while dealing with robotic manipulators to ensure that the entire scientific community are working under the same conventions.
- Number the link sequentially from $0$ to $n$. Giving us $n+1$ links.
- Number the joints sequentially from $1$ to $n$, Giving us $n$ joints.
- Number of co-ordinate frames: $n+1$
- The $Z_i$ axis is aligned with the $(i+1)^th$ joint axis.
- $X_i$ is defined along the common normal between the $Z_i$ and $Z_{i-1}$ axis.(Common normal is the line which is perpendicular to both of these axes.)
- $Y_i$ is obtained via cross product between $Z_i$ and $X_i$ axis.
- The origin is placed at this point of intersection of $x_i$, $y_i$ and $z_i$
- We define $H_i$(which is the point of intersection of the common normal of the next axis with the current axis.), and 4 new terms:
  - $a_i$ - Offset distance between two adjacent joint axes(The distance between $O_i$ and $H_{i-1}$)
  - $d_i$ - Distance between $H_{i-1}$ and $O_{i-1}$
  - $\alpha_i$ Angle between $Z_i$ and $Z_{i-1}$ when viewed from $X_i$, this is also known as the twist angle.
  - $\theta_i$ Angle between $X_i$ and $X_{i-1}$ when viewed from $Z_i$,

For a 3R Planar serial chain manipulator:
|             | a_i | d_i | $\alpha_{i}$ | \theta_i |
|-------------+-----+-----+---------+-----|
| Joint i = 1 | L_1 |   0 |       0 | \theta_1 |
| Joint i = 2 | L_2 |   0 |       0 | \theta_2 |
| Joint i = 3 | L_3 |   0 |       0 | \theta_3 |
