#+TITLE: Modelling, Simulation And Analysis.
#+AUTHOR: Adithya Nair
#+LATEX_HEADER: \input{preamble}
#+LATEX_CLASS: report
* Course Overview
:PROPERTIES:
:CUSTOM_ID: course-overview
:END:
1. Introduction to Modelling

2. Bond graph modelling

3. Basic System Models

* Unit 1
This is a precursor to the real class.

An example of the use of modelling, in a somewhat humourous approach is
through the use of a girl and boy's love story.

Let's take two functions \(G(t)\) and \(B(t)\). These functions output
the 'feelings' of the girl and the boy.

Then, \[\begin{aligned}
    \frac{dG(t)}{dt} = cG(t) + dB(t) \\
    \frac{dB(t)}{dt} = aB(t) \pm bG(t) \\
\end{aligned}\] These constants represent some influence on the change
in the feelings due to the current feelings you and your significant
other can have.

Here's another example:

Model chocolate consumption and the way it leads to happiness. State the
variables: \[\begin{aligned}
    C(t) - \text{Chocolates consumed at a given day}\\
    H(t) - \text{Happiness on a given day}
\end{aligned}\] The model for these would work like this.
\[\begin{aligned}
    \frac{dC(t)}{dt} = \alpha C(t) + \beta H(t) \\
    \frac{dH(t)}{dt} = \delta C(t) + \gamma H(t) \\
\end{aligned}\] The amount of chocolate depends on our happiness as well
as the chocolates already consumed.

** Introduction to Modelling
*** Terminology
1. *Modelling* - Refers to the development of a mathematical
   representation of a system.

2. *Simulation* - Refers to the procedure of solving the equations that
   result from model development.

3. *Mechanics* - Study of the physics of moving and static objects

4. *Dynamics* - Study of moving objects

The steps in the design of dynamic systems involve:

- A physical system, which is represented using an engineering model

- The engineering model, is represented using a bond graph technique,
  block diagrams or classical method.

- This model is then represented using differential equations

- The equations are solved using simulation software.

This course is mainly going to use the bond graph technique.

*** System
:PROPERTIES:
:CUSTOM_ID: system
:END:
A system is an aggregation or assemblage of objects joined in some
regular interaction or interdependence. This definition holds good for
static systems, and our course focuses on dynamic systems. Systems
consist of objects, with certain defined properties. These properties
lead to interactions which causes a change in the system. Such objecsts
of interest are known as entities, the properties of these entities are
known as attributes, process that causes dchange in the system are known
as activities and the complete decscription of entities attributes
activities is known as the state.

The environment containing the system and surrounding it is known as the
system environment. Endogenous decribes activities occuring inside the
system. Exogeneous describes activities in the invironment that affect
the system.

A closed system is a system with no exogeneous activity. An open system
is a system with exogeneous activites. If the outcomes are predictable,
it's deterministic. If they are random and vary with a set probability,
they are said to be stochastic. If the outcomes are smooth, then it's
said to be continuous. If the outcomes are discontinuous, then it's said
to be discrete.

*** Types Of Models
:PROPERTIES:
:CUSTOM_ID: types-of-models
:END:
**** Static Models
:PROPERTIES:
:CUSTOM_ID: static-models
:END:
Static models represents a system at a point where it is in balance,
time is not a factor. They include economic equilibrium models, they can
be used to determine the price and quanityt in markets at a single point
in time, when supply equals demand. They can be used in things like
stress-strain analysis due to time independent changes.

**** Dynamic Models
:PROPERTIES:
:CUSTOM_ID: dynamic-models
:END:
Static models represents a system at a point where it is not in balance,
time is a factor. These include:

1. Epidemic models

2. Climate models

3. Control Systems Models

4. Population Dynamics

The categorization is:

- Physical

  - Static - Architectural models, scale models of buildings used in
    architecture to test design

  - Dynamic - Models of human organs used in education

- Mathematical

  - Static

    - Numerical - Linear programming, static finite element analysis

    - Analytical - Closed form solutions, economic equilibrium

  - Dynamic

    - Numerical - Numerical Integration of differential equations, time
      stepping methods for fluid dynamics.

*** Steps Of Analytical Modelling
:PROPERTIES:
:CUSTOM_ID: steps-of-analytical-modelling
:END:
You start with:

1. Purpose of the model

   - Model to be developed should be decided based on intended
     objective.

2. Define boundaries

   - System is separated from the rest of the world, by a boundary.

   - Boundary may be real or imaginary.

   - Boundaries should be defined based on purpose.

3. Postulate a structure

   - Systems store, dissipate, transfer or transform energy from one
     form to another.

   - Identify simple elements which characterize these operations on
     energy.

   - Model elements generally have two ports, sometimes more.

   - Represent the actual system as an interconnection of these
     elements.

   - Referred to as physical modelling.

4. Select variables of interest

   - First step

   - Assign variabls to all system attributes of interest like current,
     velocity, temperature etc.

5. Math description of each model element

   - Identify the relations between variables.

   - Relations may be differential ro algebraic expressions.

6. Apply relevant physical laws.

   - The most important step.

   - Develop equations to describe the effects.

   - Physical laws describe these effects.

7. Final form of mathematical model

   - All the equations form the final mathematical model of the system.

8. Analyse and validate model

   - Model is never a exact representation.

   - Verify accuracy

   - Compare results with actual results.

9. Modify model if necessary.

   - To be done if results are not convincing

Project note - Search Varun Kumar R S, Naveen Kumar R. Go through their
papers.
