#+title: 23AID213 Operating Systems
#+author: Adithya Nair
#+EXPORT_FILE_NAME: exports/23AID213-operating-systems

* Syllabus
** Unit 1
Operating systems, structure, operating systems services, system calls. Process and Processor management: Process concepts, process scheduling and algorithms, threads, multithreading. CPU scheduling and scheduling algorithms.
** Unit 2
Process synchronization, critical sections, Deadlock: Shared resources, resource allocation and scheduling, resource graph models, deadlock detection, deadlock avoidance, deadlock prevention algorithms, mutual exclusion, semaphores, monitors, wait and signal procedures. Memory management: contiguous memory allocation, virtual memory, paging, page table structure, demand paging, page replacement policies, thrashing, segmentation.
** Unit 3
Disk scheduling algorithms and policies, File management: file concept, types and structures, directory structure,Case study on Unix (about process management, Thread management and Kernel) and Mobile OS – iOS and Android – Architecture and SDK Framework, Media Layer, Services Layer, Core OS Layer, File System)

* Assignments
