#+TITLE: Modelling, Simulation And Analysis.
#+AUTHOR: Adithya Nair
#+LATEX_HEADER: \input{preamble}
#+LATEX_CLASS: report
* Notes
** Course Overview
1. Introduction to Modelling
2. Bond graph modelling
3. Basic System Models

The textbooks to be followed is: "System Dynamics - Modeling, Simulation And Control Systems", "Modern Control Engineering, Katsuhiko Ogata"

What is modelling? It's a mathematical representation of a system. These representations allow us to evaluate the results of that given system. This course is focused on equipping us with the working knowledge to develop such mathematical models for our systems.

Upon modelling the system, we can start controlling this system. With the equations we have made, we can now add our own inputs to those equations. This in a nutshell is what the course is about.

You can use the main gnuplot configuration file for storing your settings. Otherwise you can create small files storing only one particular thing, like the color definitions as color.cfg and then load them with
** Unit 1
*** What Is Modelling?
 - Model - Models of the systems are simplified, abstracted constructs used to predict their behaviour.
 - Mathematical Modelling - Predicts only a certain aspect of the behaviour
*** Uses Of Modelling
Modelling consists of input variables $U$, which performs certain operations on a dynamic system $S$, with state variables $X$ to give some output variables $U$.
Analysis means that given an input for the present, and the system itself.

We can predict the outputs for the future. To exert some form of control, the system $S$ are used. Another term used is identification, identification means that you already $U$, and $Y$. We know the inputs and the outputs, and we map $U$ to $Y$ with the system $S$. We *identify* the system that would map the inputs to the outputs. This is done by experimenting and figuring out what mapping works best to generate the outputs from the inputs. The way to tell whether a model is good is to see if it is consistent with large sets of input and outputs.
