#+title: Journal Club
#+author: Adithya Nair
The textbook is Terrence Tao's Analysis 1.
* Real Analysis
Real Analysis is useful for engineers and physicists. It's said to have a bad reputation, due to its rigour. This textbook offsets that by starting at the very base, the numbers themselves. It starts by defining natural numbers, then building integers, rational, real, complex and so on.
We have the continuous medium which is expressed by the PDEs, Dynamics expressed by ODEs. Computer scientists aren't taught this,  they're taught Discrete Math.
** Natural Numbers
Numbers were built to count. A system for counting was made, and that system is the number system.

\begin{definition}
A natural number is an element of the set \mathbb{N} of the set
\[
\mathbb{N} = \{0,1,2,3\cdots \}
\]
is obtained from 0 and counting forward indefinitely.
\end{definition}
We start with axioms to help clarify this.

Axiom 1 : $0 \in \mathbb{N}$
Axiom 2: If $n \in \mathbb{N}$,, then $n++ \in \mathbb{N}$
This means that we have 0, 0++, ((0++)++)++ ...
We can then give these numbers  symbols for ease, 0,1,2,3... NOTE: They do not hold any quantity as yet. They simply exist as representations of 0, 0++ and so on.
Axiom 3: 0 is not an increment of any other natural number $n \in \mathbb{N}$
Axiom 4: If $n \neq m, $n++ \neq m++$
We need to remove the rogue elements from the set, such as fractions and half-integers.
Axiom 5: (Principle Of Mathematical Induction)
